#define folder variables
readgz="0_fastq.gz/"
fastq="1_fastq/"
trimming="2_trimming/"
fastqc="3_fastqc/"
kraken="4_kraken/"
metaphlan="4_metaphlan/"
spades="5_spades/"
quast="6_quast/"
qualimap="7_qualimap/"
refgenome="ref_genome/"
